---

# apt related OS tasks

- name: apt dist-upgrade
  apt:
    upgrade: dist
    autoremove: true

- name: install additional packages
  apt:
    name:
      - nginx-full
      - openssl
      - python3-openssl
    autoremove: true
    state: latest
