---
# vars file for mariadb

mariadb_conf_dir:
  RedHat: /etc/my.cnf.d
  Debian: /etc/mysql/mariadb.conf.d/

mariadb_socket:
  RedHat: /var/lib/mysql/mysql.sock
  Debian: /var/run/mysqld/mysqld.sock

mariadb_yum_repopath:
  Amazon: http://{{ mariadb_mirror_server }}/mariadb/mariadb-{{ mariadb_version }}.{{ mariadb_version_minor }}/yum/centos7-amd64
  CentOS: http://{{ mariadb_mirror_server }}/mariadb/mariadb-{{ mariadb_version }}.{{ mariadb_version_minor }}/yum/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version|int }}-amd64
  Fedora: http://{{ mariadb_mirror_server }}/mariadb/mariadb-{{ mariadb_version }}.{{ mariadb_version_minor }}/yum/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version|int }}-amd64
